### ISSUE TITLE
No such element from Selenium

### ISSUE THREAD

**Issue by eleanor-em** [matomatical/UoM-WAM-Spam#2]
This happened after a few hours! I'm running the raspbian variant of Debian stretch, standard python 3.7 environment.
```
Waking up!
Scraping WAM...
Setting up the web driver
Logging in to the results page
Traceback (most recent call last):
  File "/home/pi/scripts/UoM-WAM-Spam/wamspam.py", line 258, in <module>
    main()
  File "/home/pi/scripts/UoM-WAM-Spam/wamspam.py", line 126, in main
    poll_and_email()
  File "/home/pi/scripts/UoM-WAM-Spam/wamspam.py", line 136, in poll_and_email
    new_wam_text = scrape_wam()
  File "/home/pi/scripts/UoM-WAM-Spam/wamspam.py", line 190, in scrape_wam
    usernamebox = d.find_element_by_id("ctl00_Content_txtUserName_txtText")
  File "/home/pi/scripts/UoM-WAM-Spam/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/pi/scripts/UoM-WAM-Spam/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/scripts/UoM-WAM-Spam/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/scripts/UoM-WAM-Spam/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"ctl00_Content_txtUserName_txtText"}
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=72.0.3626.121,platform=Linux 4.19.42-v7+ armv7l)
```

**Comment by matomatical** [comment]
Thoughts:

* There's a chance that all we need to do is increase the implicit wait timeout, i.e. the page may be taking longer than 5 seconds to load the login form for some reason, which would cause this specific error.

* I'll prioritise hardening the script with exception handling, so that these kinds of failures are more graceful. In particular, it's really bad if someone is relying on the script to run continuously in the background (or on a VPS/Pi/etc.) and it crashes. Ideally, using forever shouldn't even be necessary.

* This could also be related to a memory issue. My VPS also has only 1GB of RAM and I was having all sorts of inexplicable crashes when using Firefox. Switching to Chromium fixed them temporarily, but I just learned that my script crashed shortly after I launched it anyway.

* Long- (or medium-) term, moving to a less fragile (and lighter) solution using requests+bs4 over selenium+browser sounds like it will fix this issue anyway. See #3.
